import "./globals.css";

export const metadata = {
  title: "وب سایت رسمی گلستان",
  description: "Generated by Marjan shabbak",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="flex flex-col bg-gray-200">{children}</body>
    </html>
  );
}
